name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[Release]') }}

    steps:

      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 12
          distribution: 'adopt'

      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
        run: |
            echo $ENCODED_STRING | base64 -di > "pio/signing_keystore.jks"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}

      - name: Retrieve version
        run: |
          source gradle.properties || true
          echo VERSIONCODE=`date +%s` >> $GITHUB_ENV
          VERSION=${appVerName}.$(echo ${{ github.event.head_commit.id }} | head -c 10)
          echo VERSION=${appVerName}.$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
          sed -i "s/versionname/${VERSION}/g" pio/src/main/res/values/strings.xml
      - name: Build with Gradle
        run: bash ./gradlew -PappVerName=${{ env.VERSION }} -PappVerCode=${{ env.VERSIONCODE }} assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: snapshot
          path: |
              ${{ github.workspace }}/pio/build/outputs/apk
              ${{ github.workspace }}/pio/build/outputs/mapping
      - name: Post to channel
        if: contains(github.event.head_commit.message, '[skip post]') == false
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MODULE: "${{ github.workspace }}/pio/build/outputs/apk/release/pio-release.apk"
          COMMIT_MESSAGE: |+
            ${{ github.event.head_commit.message }}
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://module%22,%22caption%22:${ESCAPED}%7D%5D"  -F module="@$MODULE"
